


<?php
  ob_start();
?>
    
    <div class="row">    
                 <div class="col-8">
                  <div class="row bg-transparent" id="map"  style="height:600px"></div>
                 </div>
                 <div class="col-4">
                  <div  id="detail"></div>
                </div>
   </div>              

 

<script type="text/javascript">
$(document).ready(function () {

 
 
  
/* formulaire*/
/*************/
  var assetUrl = "<?php echo home_base_url(); ?>";
  var url="<?php echo base_url() ?>";
 

/*Data   */
/*********/



 /* MAP*/
/*************/

    // defini map niveau region 
      
  var map = L.map('map').setView([-18.7785704655, 46.830888048], 5);
  addLayerNational().addTo(map);

  var LeafIcon = L.Icon.extend({
    options: {
       iconSize:     [30, 30],
       iconAnchor: [15,25],
       popupAnchor:  [-3, -76]
    }
});

var greenIcon = new LeafIcon({
    iconUrl: assetUrl+'/images/picto-flamme.png'
})

//var marker = new L.Marker([-17.8345566, 49.8308880],{icon: greenIcon});
//marker.addTo(map);
  
  var listFeu=<?php echo json_encode($dataToload);?>;
  for (var i=0; i<listFeu.length;i++){
                createMarker(listFeu[i].LATITUDE ,listFeu[i].LONGITUDE,listFeu[i].ID_FEU);
  }
  
  
   function addLayerNational (){
     let madagascarlayer = L.tileLayer(assetUrl+'images/communeAll/{z}/{x}/{y}.png', {
        
                      minZoom: 6,
                      maxZoom: 10,
                      tms: false,
                      attribution: 'Generated by HayTic',
                      style:function (feature) {
                        return { color: 'red', weight: 4 };
                      }
                    });
      return madagascarlayer;
   }

   

  function createMarker(latitude,longitude,popupContent){
    L.marker([latitude,longitude],{icon: greenIcon}).addTo(map).on('click',function(e){
         var sql="select ID_FEU, ID_PLANTATION, SURFACE_BRULEE,DATE_CONSTAT,DATE_INTERVENTION,ORIGINE_FEU,NOMBRE_TOUCHE,LONGITUDE,LATITUDE from lutte_active_feu where ID_FEU='"+popupContent+"'";
         $.ajax({
              url: url+'index.php/activite.php/getList',
              type:"POST",
               dataType: "json",
               data:{sql:sql},
               success: function(data) {  
                 $("#detail").html("");
                htmlDetail="";
                htmlDetail=htmlDetail+"<p> <strong>Surface brulée:</strong>"+data[0].SURFACE_BRULEE+" Ha</p>";
                htmlDetail=htmlDetail+"<p> <strong>Date constat:</strong>"+data[0].DATE_CONSTAT+"</p>";
                htmlDetail=htmlDetail+"<p> <strong>Date intervention:</strong>"+data[0].DATE_INTERVENTION+"</p>";
                htmlDetail=htmlDetail+"<p> <strong>Orgine feu:</strong>"+data[0].ORIGINE_FEU+"</p>";
                htmlDetail=htmlDetail+"<p> <strong>Nombre plants touchés:</strong>"+data[0].NOMBRE_TOUCHE+" Ha</p>";
                htmlDetail=htmlDetail+"<p> <strong>Longitude:</strong>"+data[0].LONGITUDE+"</p>";
                 htmlDetail=htmlDetail+"<p> <strong>Latitude:</strong>"+data[0].LATITUDE+"</p>";
                $("#detail").html(htmlDetail);
              }, 
               beforeSend: function() {
                                            },
               error :  function(e){
                console.log(e);
              }      
                                       
    });


      });
  }
  


 });

</script>
<?php
  
  include 'loginWithOutRegister.php';
  $content = ob_get_clean();
  include 'baseLayout.php';
?>