
<?php
  ob_start();
  //include 'donneeTabulaire.php';
?>

 <link rel="stylesheet" href="<?php echo home_base_url();?>plugins/fontawesome-free/css/all.min.css">
<div class="container"> 

<div class="row">    
                 

                <div class="col-4 mt-4">
                 <div class="input-group input-group-sm">
                      <input class="form-control border-warning" type="search" placeholder="Search" size=6 aria-label="Search" id="id">
                      <div class="input-group-append">
                        <button class="btn btn-navbar " type="button" id="btnSearch">
                          <i class="fas fa-search"></i> 
                        </button>
                      </div>
                </div>

</div>  

<div class="row"> 
  <div class="col-12 col-sm-12 col-md-12 border-warning display-6">   
              <fieldset disabled>
                  <?php echo $formulaire; ?>
             </fieldset> 
</div>
</div>

<div class="row mt-4">
    <strong><u>Suivi Feu:</u></strong>
     <table id="tabData" class="display" ></table>
    <strong><u>Taux de reussite:</u></strong>
     <table id="tabData1" class="display" ></table>
    <Strong>Carte:</Strong>
    <div class="bg-transparent" id="map"  ></div>     
</div>



    

                         

<script>

$(document).ready(function () {

 var dataSet=<?php echo json_encode($dataToload);?>;

 $.each( dataSet[0], function( key, value ) {
  $("#"+key).val(value); 
 });


 var url="<?php echo base_url() ?>";
 $('#btnSearch').click(function(){
        window.location = url+"index.php/activite.php/plantationFicheTechnique?idPlantation="+$("#id").val();
    });

var dataSetFeu=<?php echo json_encode($dataToloadFeu);?>;
var arrayCol = <?php echo json_encode($listChampsFeu); ?>;
var cols =[];
  for (var i=0; i<arrayCol.length;i++){
    if (arrayCol[i].type!=="select"){
      aCol ={};
               aCol.data=arrayCol[i].nom;
               aCol.title=arrayCol[i].libelle;
               cols.push(aCol);
    }
               
  }

var tab=$('#tabData').DataTable( {
                aaData: dataSetFeu, 
                dataType: 'json',
                dom: 'iftrp',
                select: 'single',
                scrollX:true,
                columns: cols,
                pageLength:5,

                } );

var dataToloadTauxReussite=<?php echo json_encode($dataToloadTauxReussite);?>;
var arrayColTauxResussite = <?php echo json_encode($listChampsTauxReussite); ?>;

var cols =[];
  for (var i=0; i<arrayColTauxResussite.length;i++){
    if (arrayColTauxResussite[i].type!=="select"){
      aCol ={};
               aCol.data=arrayColTauxResussite[i].nom;
               aCol.title=arrayColTauxResussite[i].libelle;
               cols.push(aCol);
    }
               
  }
var tab1=$('#tabData1').DataTable( {
                aaData: dataToloadTauxReussite, 
                dataType: 'json',
                dom: 'iftrp',
                select: 'single',
                scrollX:true,
                columns: cols,
                pageLength:5
                } );

/*****MAP****/

 var assetUrl = "<?php echo home_base_url(); ?>";

  var map = L.map('map').setView([-18.7785704655, 46.830888048], 5);

  var LeafIcon = L.Icon.extend({
    options: {
       iconSize:     [25, 25],
       iconAnchor: [12,25],
       popupAnchor:  [-3, -76]
    }
});

var greenIcon = new LeafIcon({
    iconUrl: assetUrl+'/images/pepiniere.png'
})
addLayerNational().addTo(map);
function addLayerNational (){
     let madagascarlayer = L.tileLayer(assetUrl+'images/region/{z}/{x}/{y}.png', {
        
                      minZoom: 5,
                      maxZoom: 10,
                      tms: false,
                      attribution: 'Generated by HayTic',
                      style:function (feature) {
                        return { color: 'red', weight: 4 };
                      }
                    });
      return madagascarlayer;
   }

function addShapeFile(){

    var shpfile = new L.Shapefile(assetUrl+'images/shapefile.zip', {
      onEachFeature: function(feature, layer) {
        if (feature.properties) {
          layer.bindPopup(Object.keys(feature.properties).map(function(k) {
            return k + ": " + feature.properties[k];
          }).join("<br />"), {
            maxHeight: 200
          });
        }
      }
    });
    return shpfile;
  
   }   

});

</script> 


<script src="<?php echo home_base_url();?>plugins/jquery/jquery.min.js" type="text/javascript"></script>
<script src="<?php echo home_base_url();?>js/jquery.dataTables.min.js" type="text/javascript"></script> 



<script src="<?php echo home_base_url();?>js/dataTables.buttons.min.js"></script>






<script src="<?php echo home_base_url();?>plugins/jszip/jszip.min.js"></script>
<script src="<?php echo home_base_url();?>plugins/pdfmake/pdfmake.min.js"></script>
<script src="<?php echo home_base_url();?>plugins/pdfmake/vfs_fonts.js"></script>
<script src="<?php echo home_base_url();?>plugins/datatables-buttons/js/buttons.html5.min.js"></script>
<script src="<?php echo home_base_url();?>plugins/datatables-buttons/js/buttons.print.min.js"></script>
<script src="<?php echo home_base_url();?>/plugins/datatables-buttons/js/buttons.colVis.min.js"></script>
<script src="<?php echo home_base_url();?>plugins/jquery-ui/jquery-ui.js"></script>


<link rel="stylesheet" type="text/css" href="<?php echo home_base_url();?>css/jquery.dataTables.min.css">
<link rel="stylesheet" type="text/css" href="<?php echo home_base_url();?>css/dataTables.checkboxes.css">
<link rel="stylesheet" type="text/css" href="<?php echo home_base_url();?>css/jquery.dataTables.min.css">
<link rel="stylesheet" type="text/css" href="<?php echo home_base_url();?>css/buttons.dataTables.min.css">
<link rel="stylesheet" type="text/css" href="<?php echo home_base_url();?>plugins/jquery-ui/jquery-ui.css">

<script src="<?php echo home_base_url();?>js/dataTables.select.min.js" type="text/javascript"></script>

<link rel="stylesheet" href="<?php echo home_base_url();?>plugins/fontawesome-free/css/all.min.css">

<link rel="stylesheet" type="text/css" href="<?php echo home_base_url();?>css/reboisement.css">


<!-- Bootstrap 4 -->
<script src="<?php echo home_base_url();?>plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
<!-- AdminLTE App -->
<script src="<?php echo home_base_url();?>dist/js/adminlte.min.js"></script>
<!-- jQuery UI 1.11.4 -->
<script src="<?php echo home_base_url();?>plugins/jquery-ui/jquery-ui.min.js"></script>
<!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->
<script>
  $.widget.bridge('uibutton', $.ui.button)
</script>

<!-- ChartJS -->
<script src="<?php echo home_base_url();?>plugins/chart.js/Chart.min.js"></script>

 <link rel="stylesheet" href="<?php echo home_base_url();?>dist/css/adminlte.min.css">